### ISSUE TITLE
Easy To Remember error still generates password

### ISSUE THREAD

**Issue by RascalTwo** [RascalTwo/PythonBuddiesPasswordGenerator#15]
A Password is still generated when shown the warning

> "Length must be equal to or loger than your name and birth year"

in the Easy To Remember frame.

**Comment by jangrd** [comment]
Fixed it. It was missing a `return`

**Comment by RascalTwo** [comment]
Closed by fe0aa09b5712e130de17ff998a8a0b4ce830ea1c
